version: 0.3.{build}
configuration: Release
platform: Any CPU
cache: ReactiveServices/packages
before_build:
- nuget restore ReactiveServices/ReactiveServices.Authorization.sln
after_build:
- nuget pack ReactiveServices/ReactiveServices.Authorization.csproj -IncludeReferencedProjects -Properties Configuration=Release -Properties Platform=AnyCPU
build:
  project: ReactiveServices/ReactiveServices.Authorization.sln
  verbosity: minimal
test:
  categories:
    except:
      - failing
      - unstable
      - slow
      - load
assembly_info:
  patch: true
  file: ReactiveServices\Authorization\Properties\AssemblyInfo.cs
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: ReactiveServices.Authorization.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: f16K1osClAxbT+GmqxPPFj//CRk7rOFm4XtRVJkGTqnvfQwR30LPgTidxUSzRLyd
  skip_symbols: true